import { db, NavigationTable, CategoryTable, AreaTable, SpotTable, WeatherTable } from 'astro:db';

export default async function seed() {
  await db.insert(NavigationTable).values([
    { id: 1, url: '/', name: 'TOP', description: 'トップ' },
    { id: 2, url: 'news', name: 'NEWS', description: 'ニュース' },
    { id: 3, url: 'open', name: 'OPEN', description: '開店・閉店' },
    { id: 4, url: 'events', name: 'EVENTS', description: 'イベント' },
    { id: 5, url: 'city', name: 'CITY', description: '行政・暮らし' },
    { id: 6, url: 'develop', name: 'DEVELOP', description: '再開発・まちづくり' },
  ]);

  await db.insert(CategoryTable).values([
    { id: 1, name: 'ニュース', slug: 'news' },
    { id: 2, name: '開店・閉店', slug: 'open' },
    { id: 3, name: 'イベント', slug: 'events' },
    { id: 4, name: '行政・暮らし', slug: 'city' },
    { id: 5, name: '再開発・まちづくり', slug: 'develop' },
    { id: 6, name: 'その他', slug: 'others' },
  ]);

  await db.insert(AreaTable).values([
    { id: 1, name: 'サンポート', slug: 'sunport' },
    { id: 2, name: '高松駅前', slug: 'takamatsu-station' },
    { id: 3, name: '中央商店街', slug: 'central-arcade' },
    { id: 4, name: '瓦町', slug: 'kawaramachi' },
    { id: 5, name: '栗林', slug: 'ritsurin' },
    { id: 6, name: 'レインボーロード', slug: 'rainbow-road' },
    { id: 7, name: '屋島', slug: 'yashima' },
    { id: 8, name: '仏生山', slug: 'busshozan' },
    { id: 9, name: '国分寺', slug: 'kokubunji' },
    { id: 10, name: '牟礼・庵治', slug: 'mure-aji' },
  ]);

  await db.insert(SpotTable).values([
    // サンポート
    {
      id: 1,
      areaId: 1,
      name: 'サンポート高松',
      slug: 'sunport-takamatsu',
    },
    {
      id: 2,
      areaId: 1,
      name: 'あなぶきアリーナ香川',
      slug: 'anabuki-arena-kagawa',
    },
    {
      id: 3,
      areaId: 1,
      name: '高松シンボルタワー',
      slug: 'symbol-tower',
    },

    // 高松駅前
    {
      id: 4,
      areaId: 2,
      name: 'JR高松駅',
      slug: 'jr-takamatsu-station',
    },
    {
      id: 5,
      areaId: 2,
      name: '高松オルネ',
      slug: 'takamatsu-orne',
    },
    {
      id: 6,
      areaId: 2,
      name: '玉藻公園',
      slug: 'tamamo-park',
    },

    // 中央商店街
    {
      id: 7,
      areaId: 3,
      name: '丸亀町商店街',
      slug: 'marugamemachi',
    },
    {
      id: 8,
      areaId: 3,
      name: '丸亀町グリーン',
      slug: 'marugamemachi-green',
    },
    {
      id: 9,
      areaId: 3,
      name: '兵庫町商店街',
      slug: 'hyogomachi',
    },
    {
      id: 10,
      areaId: 3,
      name: 'ライオン通商店街',
      slug: 'lion-dori',
    },
    {
      id: 11,
      areaId: 3,
      name: '南新町商店街',
      slug: 'minamishinmachi',
    },

    // 瓦町
    {
      id: 12,
      areaId: 4,
      name: '瓦町FLAG',
      slug: 'kawaramachi-flag',
    },
    {
      id: 13,
      areaId: 4,
      name: '瓦町駅',
      slug: 'kawaramachi-station',
    },
    {
      id: 14,
      areaId: 4,
      name: 'トキワ街',
      slug: 'tokiwa-street',
    },

    // 栗林
    {
      id: 15,
      areaId: 5,
      name: '栗林公園',
      slug: 'ritsurin-garden',
    },
    {
      id: 16,
      areaId: 5,
      name: '栗林駅',
      slug: 'ritsurin-station',
    },

    // レインボーロード
    {
      id: 17,
      areaId: 6,
      name: 'レインボーロード',
      slug: 'rainbow-road-main',
    },
    {
      id: 18,
      areaId: 6,
      name: 'サンフラワー通り',
      slug: 'sunflower-road',
    },

    // 屋島
    {
      id: 19,
      areaId: 7,
      name: '屋島山上',
      slug: 'yashima-mountain',
    },
    {
      id: 20,
      areaId: 7,
      name: '屋島寺',
      slug: 'yashimaji',
    },

    // 仏生山
    {
      id: 21,
      areaId: 8,
      name: '仏生山温泉',
      slug: 'busshozan-onsen',
    },
    {
      id: 22,
      areaId: 8,
      name: '仏生山公園',
      slug: 'busshozan-park',
    },

    // 国分寺
    {
      id: 23,
      areaId: 9,
      name: '讃岐国分寺跡',
      slug: 'sanuki-kokubunji',
    },

    // 牟礼・庵治
    {
      id: 24,
      areaId: 10,
      name: '八栗駅',
      slug: 'yakuri-station',
    },
    {
      id: 25,
      areaId: 10,
      name: '庵治漁港',
      slug: 'aji-fishing-port',
    },
  ]);

  await db.insert(WeatherTable).values([
    { id: 1, code: 100, name: '晴れ', image: '100.svg' },
    { id: 2, code: 101, name: '晴れ時々くもり', image: '101.svg' },
    { id: 3, code: 102, name: '晴れ一時雨', image: '102.svg' },
    { id: 4, code: 103, name: '晴れ時々雨', image: '103.svg' },
    { id: 5, code: 104, name: '晴れ一時雪', image: '104.svg' },
    { id: 6, code: 105, name: '晴れ時々雪', image: '105.svg' },
    { id: 7, code: 106, name: '晴れ一時雨か雪', image: '106.svg' },
    { id: 8, code: 107, name: '晴れ時々雨か雪', image: '107.svg' },
    { id: 9, code: 108, name: '晴れ一時雨か雷雨', image: '108.svg' },
    { id: 10, code: 110, name: '晴れのち時々くもり', image: '110.svg' },
    { id: 11, code: 111, name: '晴れのちくもり', image: '111.svg' },
    { id: 12, code: 112, name: '晴れのち一時雨', image: '112.svg' },
    { id: 13, code: 113, name: '晴れのち時々雨', image: '113.svg' },
    { id: 14, code: 114, name: '晴れのち雨', image: '114.svg' },
    { id: 15, code: 115, name: '晴れのち一時雪', image: '115.svg' },
    { id: 16, code: 116, name: '晴れのち時々雪', image: '116.svg' },
    { id: 17, code: 117, name: '晴れのち雪', image: '117.svg' },
    { id: 18, code: 118, name: '晴れのち雨か雪', image: '118.svg' },
    { id: 19, code: 119, name: '晴れのち雨か雷雨', image: '119.svg' },
    { id: 20, code: 120, name: '晴れ朝夕一時雨', image: '120.svg' },
    { id: 21, code: 121, name: '晴れ朝のうち一時雨', image: '121.svg' },
    { id: 22, code: 122, name: '晴れ夕方一時雨', image: '122.svg' },
    { id: 23, code: 123, name: '晴れ山沿い雷雨', image: '123.svg' },
    { id: 24, code: 124, name: '晴れ山沿い雪', image: '124.svg' },
    { id: 25, code: 125, name: '晴れ午後は雷雨', image: '125.svg' },
    { id: 26, code: 126, name: '晴れ昼頃から雨', image: '126.svg' },
    { id: 27, code: 127, name: '晴れ夕方から雨', image: '127.svg' },
    { id: 28, code: 128, name: '晴れ夜は雨', image: '128.svg' },
    { id: 29, code: 130, name: '朝のうち霧のち晴れ', image: '100.svg' },
    { id: 30, code: 131, name: '晴れ明け方霧', image: '100.svg' },
    { id: 31, code: 132, name: '晴れ朝夕くもり', image: '100.svg' },
    { id: 32, code: 140, name: '晴れ時々雨で雷を伴う', image: '100.svg' },
    { id: 33, code: 200, name: 'くもり', image: '200.svg' },
    { id: 34, code: 201, name: 'くもり時々晴れ', image: '201.svg' },
    { id: 35, code: 202, name: 'くもり一時雨', image: '202.svg' },
    { id: 36, code: 203, name: 'くもり時々雨', image: '203.svg' },
    { id: 37, code: 204, name: 'くもり一時雪', image: '204.svg' },
    { id: 38, code: 205, name: 'くもり時々雪', image: '205.svg' },
    { id: 39, code: 206, name: 'くもり一時雨か雪', image: '206.svg' },
    { id: 40, code: 207, name: 'くもり時々雨か雪', image: '207.svg' },
    { id: 41, code: 208, name: 'くもり一時雨か雷雨', image: '208.svg' },
    { id: 42, code: 209, name: 'くもり時々雨で雷を伴う', image: '209.svg' },
    { id: 43, code: 210, name: 'くもりのち時々晴れ', image: '210.svg' },
    { id: 44, code: 211, name: 'くもりのち晴れ', image: '211.svg' },
    { id: 45, code: 212, name: 'くもりのち一時雨', image: '212.svg' },
    { id: 46, code: 213, name: 'くもりのち時々雨', image: '213.svg' },
    { id: 47, code: 214, name: 'くもりのち雨', image: '214.svg' },
    { id: 48, code: 215, name: 'くもりのち一時雪', image: '215.svg' },
    { id: 49, code: 216, name: 'くもりのち時々雪', image: '216.svg' },
    { id: 50, code: 217, name: 'くもりのち雪', image: '217.svg' },
    { id: 51, code: 218, name: 'くもりのち雨か雪', image: '218.svg' },
    { id: 52, code: 219, name: 'くもりのち雨か雷雨', image: '219.svg' },
    { id: 53, code: 220, name: 'くもり朝夕一時雨', image: '220.svg' },
    { id: 54, code: 221, name: 'くもり朝のうち一時雨', image: '221.svg' },
    { id: 55, code: 222, name: 'くもり夕方一時雨', image: '222.svg' },
    { id: 56, code: 223, name: 'くもり日中一時雨', image: '223.svg' },
    { id: 57, code: 224, name: 'くもり昼頃から雨', image: '224.svg' },
    { id: 58, code: 225, name: 'くもり夕方から雨', image: '225.svg' },
    { id: 59, code: 226, name: 'くもり夜は雨', image: '226.svg' },
    { id: 60, code: 228, name: 'くもり昼頃から雪', image: '228.svg' },
    { id: 61, code: 229, name: 'くもり夕方から雪', image: '229.svg' },
    { id: 62, code: 230, name: 'くもり夜は雪', image: '230.svg' },
    { id: 63, code: 231, name: '海上に見かけ上の霧', image: '200.svg' },
    { id: 64, code: 270, name: 'くもり時々薄日', image: '270.svg' },
    { id: 65, code: 281, name: 'くもりづのち雪か雨', image: '200.svg' },
    { id: 66, code: 300, name: '雨', image: '300.svg' },
    { id: 67, code: 301, name: '雨時々晴れ', image: '301.svg' },
    { id: 68, code: 302, name: '雨時々くもり', image: '302.svg' },
    { id: 69, code: 303, name: '雨時々雪', image: '303.svg' },
    { id: 70, code: 304, name: '雨か雪', image: '304.svg' },
    { id: 71, code: 306, name: '大雨', image: '306.svg' },
    { id: 72, code: 308, name: '雨で暴風を伴う', image: '308.svg' },
    { id: 73, code: 309, name: '雨一時雪', image: '309.svg' },
    { id: 74, code: 311, name: '雨のち晴れ', image: '311.svg' },
    { id: 75, code: 313, name: '雨のちくもり', image: '313.svg' },
    { id: 76, code: 314, name: '雨のち時々雪', image: '314.svg' },
    { id: 77, code: 315, name: '雨のち雪', image: '315.svg' },
    { id: 78, code: 316, name: '雨か雪のち晴れ', image: '316.svg' },
    { id: 79, code: 317, name: '雨か雪のちくもり', image: '317.svg' },
    { id: 80, code: 320, name: '朝のうち雨のち晴れ', image: '320.svg' },
    { id: 81, code: 321, name: '朝のうち雨のちくもり', image: '321.svg' },
    { id: 82, code: 322, name: '雨朝晩一時雪', image: '322.svg' },
    { id: 83, code: 323, name: '雨昼頃から晴れ', image: '323.svg' },
    { id: 84, code: 324, name: '雨夕方から晴れ', image: '324.svg' },
    { id: 85, code: 325, name: '雨夜は晴れ', image: '325.svg' },
    { id: 86, code: 326, name: '雨夕方から雪', image: '326.svg' },
    { id: 87, code: 327, name: '雨夜は雪', image: '327.svg' },
    { id: 88, code: 328, name: '雨一時強く降る', image: '328.svg' },
    { id: 89, code: 329, name: '雨一時みぞれ', image: '329.svg' },
    { id: 90, code: 340, name: '雪か雨', image: '340.svg' },
    { id: 91, code: 350, name: '雨で雷を伴う', image: '350.svg' },
    { id: 92, code: 361, name: '雪か雨のち晴れ', image: '361.svg' },
    { id: 93, code: 371, name: '雪か雨のちくもり', image: '371.svg' },
    { id: 94, code: 400, name: '雪', image: '400.svg' },
    { id: 95, code: 401, name: '雪時々晴れ', image: '401.svg' },
    { id: 96, code: 402, name: '雪時々くもり', image: '402.svg' },
    { id: 97, code: 403, name: '雪時々雨', image: '403.svg' },
    { id: 98, code: 405, name: '大雪', image: '405.svg' },
    { id: 99, code: 406, name: '雪で暴風を伴う', image: '406.svg' },
    { id: 100, code: 407, name: '雪一時雨', image: '407.svg' },
    { id: 101, code: 409, name: '雪一時みぞれ', image: '409.svg' },
    { id: 102, code: 411, name: '雪のち晴れ', image: '411.svg' },
    { id: 103, code: 412, name: '雪のち時々雨', image: '412.svg' },
    { id: 104, code: 413, name: '雪のちくもり', image: '413.svg' },
    { id: 105, code: 414, name: '雪のち雨', image: '414.svg' },
    { id: 106, code: 420, name: '朝のうち雪のち晴れ', image: '420.svg' },
    { id: 107, code: 421, name: '朝のうち雪のちくもり', image: '421.svg' },
    { id: 108, code: 422, name: '雪朝晩一時雨', image: '422.svg' },
    { id: 109, code: 423, name: '雪昼頃から晴れ', image: '423.svg' },
    { id: 110, code: 425, name: '雪夜は晴れ', image: '425.svg' },
    { id: 111, code: 426, name: '雪夕方から雨', image: '426.svg' },
    { id: 112, code: 427, name: '雪夜は雨', image: '427.svg' },
    { id: 113, code: 430, name: '雪一時強く降る', image: '430.svg' },
    { id: 114, code: 450, name: '雪で雷を伴う', image: '450.svg' },
  ]);
}
